AWSTemplateFormatVersion: "2010-09-09"
Description: Network Resource Example
Resources:
  PrimaryS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "primary-bettafish15-bucket"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
        IgnorePublicAcls: false
  S3AccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "cloudformation.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "S3AccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "s3:*"
                Resource: !Sub "arn:aws:s3:::${PrimaryS3Bucket}/*"
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PrimaryS3Bucket
      PolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${PrimaryS3Bucket}/*"
            Condition:
              StringEquals:
                aws:PrincipalArn: !GetAtt S3AccessRole.Arn
